CREATE TABLE [etl].[ApplicationLog](
	[ApplicationLogId] [bigint] PRIMARY KEY IDENTITY(1,1),
	[State] [varchar](20) NOT NULL,
	[IsError] [bit] NOT NULL,
	[Severity] [varchar](20) NOT NULL,
	[Environment] [varchar](20) NOT NULL,
	[CreateDate] [datetime] NOT NULL,
	[Command] [varchar](50) NULL,
	[CommandName] [varchar](50) NULL,
	[IsChainedCommand] [bit] NULL,
	[Mode] [varchar](50) NULL,
	[ModeName] [varchar](50) NULL,
	[Arguments] [varchar](50) NULL,
	[ShortMsg] [varchar](250) NULL,
	[LongMsg] [varchar](max) NULL,
	[RecordCount] [int] NULL,
	[RoundTripSec] [float] NULL,
	[ServerName] [varchar](50) NOT NULL,
	[SessionID] [uniqueidentifier] NOT NULL)