CREATE TABLE [etl].[JobLog](
	[JobLogId] [bigint] PRIMARY KEY IDENTITY(1,1),
	[IsError] [bit] NOT NULL,
	[Severity] [varchar](20) NOT NULL,
	[Environment] [varchar](20) NOT NULL,
	[CreateDate] [datetime] NOT NULL,
	[Command] [varchar](50) NULL,
	[CommandName] [varchar](50) NULL,
	[Mode] [varchar](50) NULL,
	[ModeName] [varchar](50) NULL,
	[Arguments] [varchar](50) NULL,
	[ShortMsg] [varchar](250) NULL,
	[LongMsg] [varchar](max) NULL,
	[RecordCount] [int] NULL,
	[RoundTripMs] [float] NULL,
	[Output] [varchar](max) NULL,
	[ServerName] [varchar](50) NOT NULL,
	[SessionID] [uniqueidentifier] NOT NULL)